// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzialhekgzxulsyoicet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aWFsaGVrZ3p4dWxzeW9pY2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NzgyNTgsImV4cCI6MjA2OTA1NDI1OH0.qvVqBW3EoIBakON0U8R36WNhkNY4B1WRA7bxsfN9MdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});